#ifndef DKCOOP_RECOVERY_STORAGE_H
#define DKCOOP_RECOVERY_STORAGE_H

enum {
    COOP_RECOVERY_STORAGE_CONFIGURED = 1u << 0,
    COOP_RECOVERY_STORAGE_CHECKPOINT = 1u << 1,
    COOP_RECOVERY_STORAGE_PROMOTED = 1u << 2,
    COOP_RECOVERY_STORAGE_SAVE_ADVANCED = 1u << 3,
    COOP_RECOVERY_STORAGE_ERROR = 1u << 4,
};

enum {
    COOP_RECOVERY_SAVE_HOST = 1u << 0,
    COOP_RECOVERY_SAVE_ITEMS = 1u << 1,
};

#endif
