"""Verify local US ROM metadata and generate ID/counter mappings (no assets).

Input is the user's locally decompressed ROM. Table layouts and pickup ordering
follow the pinned decomp code_135D30.c, code_36880.c and code_F9450.c.
"""
from pathlib import Path
import collections
import struct
import sys
import zlib

root = Path(__file__).resolve().parents[1]
rom = Path(sys.argv[1]).read_bytes()
def at(address, fmt):
    return struct.unpack_from(fmt, rom, 0x2000000 + address - 0x805FB300)

levels = at(0x807445E0, '>221B')
lobbies = at(0x80744734, '>9H')
def level(m):
    return 7 if m in lobbies else levels[m]

gbs = {}
for i in range(113):
    m, obj, flag, actor = at(0x80755A20 + i * 8, '>BxhhBx')
    if 0x225 <= flag <= 0x24C:  # Five Helm medals also use this prop table.
        continue
    assert 2 <= actor <= 6 and level(m) < 8 and flag not in gbs
    gbs[flag] = (level(m), actor - 2)
for i in range(53):
    flag, actor = at(0x80755F50 + i * 4, '>hBx')
    if not actor:
        assert flag == 0x1C4  # Unused bonus barrel.
        continue
    lvl = next((j for j, end in enumerate((0x30, 0x70, 0x9A, 0xCD, 0x103, 0x131, 0x17D)) if flag < end), 7)
    reward = (lvl, actor - 2)
    assert flag not in gbs or gbs[flag] == reward
    gbs[flag] = reward
# Direct scripted rewards outside the prop/barrel tables: seal race, Chunky
# minecart and Tiny castle car race (pinned decomp reward call sites).
for flag, reward in {0xA5: (3, 0), 0xD7: (4, 4), 0x145: (6, 3)}.items():
    assert flag not in gbs
    gbs[flag] = reward
assert len(gbs) == 161
distribution = collections.Counter(gbs.values())
assert all(distribution[l, k] == (5 if (l, k) == (7, 3) else 4) for l in range(8) for k in range(5))

types = {10, 13, 22, 28, 29, 30, 31, 35, 36, 39, 43, 517, 518, 519, 520}
mapping = {}
for i in range(40):
    typ, hud, _, _, _, actor, _, _, _ = at(0x80753EF0 + i * 20, '>HbBIIhhhh')
    if typ in types:
        assert typ not in mapping and hud in (0, 1) and 2 <= actor <= 6
        mapping[typ] = (actor - 2, 0 if hud == 1 else 5 if typ in (43, 517, 518, 519, 520) else 1)
assert set(mapping) == types
base = 0x101C50
table = base + struct.unpack_from('>I', rom, base + 9 * 4)[0]
pickups = [[] for _ in range(8)]
actors = []
actor_ordinal = 0
for m in range(221):
    start, end = struct.unpack_from('>II', rom, table + m * 4)
    data = zlib.decompress(rom[base + (start & 0x7FFFFFFF):base + (end & 0x7FFFFFFF)], 47)
    count = struct.unpack_from('>I', data)[0]
    assert 4 + count * 48 <= len(data)
    for i in range(count):
        typ, obj = struct.unpack_from('>HH', data, 4 + i * 48 + 40)
        if typ in types:
            assert level(m) < 8
            pickups[level(m)].append((*mapping[typ], m, obj))
    offset = 4 + count * 48
    offset += 4 + struct.unpack_from('>I', data, offset)[0] * 36
    actor_count = struct.unpack_from('>I', data, offset)[0]
    assert offset + 4 + actor_count * 56 == len(data)
    for i in range(actor_count):
        typ, obj = struct.unpack_from('>HH', data, offset + 4 + i * 56 + 50)
        typ += 16
        if typ in (0x5B, 0x6F, 0x70, 0x71, 0x72, 0x8B):
            flag = 0x26B + actor_ordinal
            actor_ordinal += 1
            if level(m) >= 8:
                assert m == 0 and typ == 0x72, (m, typ)  # Test-map balloon, not adventure.
                continue
            kong = {0x5B: 1, 0x6F: 4, 0x70: 3, 0x71: 2, 0x72: 0, 0x8B: 0}[typ]
            actors.append((flag, level(m), kong, 0 if typ == 0x8B else 10))
assert actor_ordinal == 121 and len(actors) == 120
assert sum(a[3] == 0 for a in actors) == 16
assert [len(p) for p in pickups] == [226, 263, 245, 245, 271, 194, 253, 3]
amounts = collections.Counter()
for l, rows in enumerate(pickups):
    for k, amount, _, _ in rows:
        amounts[l, k] += amount
assert all(n <= 100 for n in amounts.values())
for _, l, k, amount in actors:
    amounts[l, k] += amount
# Check setup totals, including three surplus single-banana entries. Chunky's
# Japes boulder actor drop is outside both persistent pickup tables.
expected_cb = {(0, 4): 95, (0, 0): 101, (0, 1): 101, (3, 3): 101}
assert all(amounts[l, k] == expected_cb.get((l, k), 100) for l in range(7) for k in range(5))

lines = ['// Generated by tools/generate-collectibles.py from verified local US metadata.',
         '// Only collectible IDs, counter destinations and amounts; no ROM assets.',
         '#ifndef COOP_COLLECTIBLE_IDS_H', '#define COOP_COLLECTIBLE_IDS_H',
         'typedef struct { unsigned short flag; unsigned char level, kong; } CoopGoldenBanana;',
         'static const CoopGoldenBanana coop_golden_bananas[161] = {']
lines += [f'    {{0x{flag:03X}, {l}, {k}}},' for flag, (l, k) in sorted(gbs.items())]
lines += ['};', 'typedef struct { unsigned char kong, amount; } CoopPickup;',
          '// amount 0 = one coin; amount 1/5 = colored bananas. Ordinal is per level.',
          'static const unsigned short coop_pickup_start[9] = {0, 226, 489, 734, 979, 1250, 1444, 1697, 1700};',
          'static const CoopPickup coop_pickups[1700] = {']
for l, rows in enumerate(pickups):
    lines.append(f'    // Level {l}, setup order within ascending map IDs.')
    lines += [f'    {{{k}, {amount}}}, // map {m}, object {obj}' for k, amount, m, obj in rows]
lines += ['};', 'typedef struct { unsigned short flag; unsigned char level, kong, amount; } CoopActorPickup;',
          '// amount 10 = balloon; amount 0 = rainbow coin (+5 to every Kong).',
          'static const CoopActorPickup coop_actor_pickups[120] = {']
lines += [f'    {{0x{f:03X}, {l}, {k}, {a}}},' for f, l, k, a in actors]
lines += ['};', '#endif', '']
output = '\n'.join(lines)
path = root / 'mod/collectible_ids.h'
if '--check' in sys.argv:
    assert path.read_text(encoding='utf-8') == output
else:
    path.write_text(output, encoding='utf-8')
print('PASS: 161 GBs, 1700 ordinary pickups, 104 balloons, 16 rainbow coins; all 40 GB and 35 CB buckets checked')
